name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Load .env variables globally
        run: |
          echo "Loading .env into GitHub ENV..."
          while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < .env
          echo "✅ Environment variables loaded globally"

      - name: Debug environment
        run: |
          echo "IG_USERNAME: $IG_USERNAME"
          echo "IG_PASSWORD: $IG_PASSWORD"
          echo "GROQ_API_KEY: $GROQ_API_KEY"

      - name: Run Bot
        run: |
          chmod +x igbot.py
          echo "🚀 Starting bot..."
          python3 igbot.py
