name: Auto Deploy

on:
  push:
    branches:
      - main  # jab bhi main branch me push hoga, deploy trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Give Execute Permission
        run: chmod +x *

      - name: Debug Environment Variables (optional)
        run: |
          echo "🧩 Checking environment..."
          if [ -z "$IG_USERNAME" ]; then echo "❌ IG_USERNAME missing"; fi
          if [ -z "$IG_PASSWORD" ]; then echo "❌ IG_PASSWORD missing"; fi
          if [ -z "$GROQ_API_KEY" ]; then echo "⚠️ GROQ_API_KEY missing"; fi

      - name: Run Instagram Bot
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo "🚀 Starting bot..."
          python3 igbot.py
