name: Auto Deploy

on:
  push:
    branches:
      - main  # main branch par push hote hi trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # ya version jo tu use kar raha hai

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Executable Permissions
        run: |
          chmod +x *.py
          chmod 600 .env || true  # .env safe permission
          echo "✅ Permissions set successfully"

      - name: Load Environment Variables
        run: |
          echo "Loading .env..."
          export $(grep -v '^#' .env | xargs)

      - name: Run Instagram Bot
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo "🚀 Starting bot..."
          python3 igbot.py
